### ISSUE TITLE
FeedReader.ReadAsync error with feeds with leading spaces.

### ISSUE THREAD

**Issue by binamonk** [codehollow/FeedReader#21]
FeedReader.ReadAsync method throw an error when the feed has leading spaces 

Try it with FeedReader.ReadAsync("http://gurudeviaje.com/feed/");

Exception has occurred: CLR/System.AggregateException
An unhandled exception of type 'System.AggregateException' occurred in System.Private.CoreLib.dll: 'One or more errors occurred.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.Xml.XmlException : Unexpected XML declaration. The XML declaration must be the first node in the document, and no whitespace characters are allowed to appear before it. Line 2, position 3.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParsePI(StringBuilder piInDtdStringBuilder)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at CodeHollow.FeedReader.Parser.FeedParser.GetFeed(Byte[] feedContentData)
   at CodeHollow.FeedReader.FeedReader.<ReadAsync>d__8.MoveNext()

**Comment by codehollow** [comment]
hey, issue fixed in the new version 1.1.6. Thanks for reporting!
