### ISSUE TITLE
System.Xml.XmlException: 'atom' is an undeclared prefix

### ISSUE THREAD

**Issue by Worldbeater** [codehollow/FeedReader#5]
Hello, @codehollow!

I'm experiencing XmlException when trying to read feed from: http://tjournal.ru/rss
Tested on .NETCore 2.0, NETStandard using CodeHollow.FeedReader 1.1.0.2
Debug output:
```
 "C:\Program Files\dotnet\dotnet.exe" C:/Users/User/RiderProjects/Tests/Tests/bin/Debug/netcoreapp2.0/Tests.dll
System.Xml.XmlException: 'atom' is an undeclared prefix. Line 116, position 6.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.LookupNamespace(NodeData node)
   at System.Xml.XmlTextReaderImpl.ElementNamespaceLookup()
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at CodeHollow.FeedReader.Parser.FeedParser.GetFeed(String feedContent)
   at CodeHollow.FeedReader.FeedReader.<ReadAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Tests.Program.<MainAsync>d__1.MoveNext() in C:\Users\User\RiderProjects\Tests\Tests\Program.cs:line 18
```
Sample code to reproduce the issue:
```c#
static async void MainAsync() {
    try {
        var feed = await FeedReader.ReadAsync("http://tjournal.ru/rss");
        Console.Write(feed);
    } catch (Exception e) {
        Console.WriteLine(e);
    }
}
```
Thanks in advance!

**Comment by Worldbeater** [comment]
Everything works fine for now: seems that this website has recently added missing "atom" prefix to some of xml tags in the generated feed. So I close the issue -- there is no need to fix anything in the library.
